// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmOgPeJNmQbDN1UC2kjIFw0H1wkVN_X0Y',
    appId: '1:748534742676:web:d9a1311666f46dbd20fe81',
    messagingSenderId: '748534742676',
    projectId: 'flutter-project-61700',
    authDomain: 'flutter-project-61700.firebaseapp.com',
    storageBucket: 'flutter-project-61700.firebasestorage.app',
    measurementId: 'G-HPKP68XEF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO3lEAm5DhwSdKxTvhKdPkyRCbA6WULhY',
    appId: '1:748534742676:android:5a856dd9179fa5bc20fe81',
    messagingSenderId: '748534742676',
    projectId: 'flutter-project-61700',
    storageBucket: 'flutter-project-61700.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8qgOFt7qDQc644pMY1Wy-d87WmQc_sAE',
    appId: '1:748534742676:ios:6cbda1a40c9c117020fe81',
    messagingSenderId: '748534742676',
    projectId: 'flutter-project-61700',
    storageBucket: 'flutter-project-61700.firebasestorage.app',
    iosBundleId: 'com.example.flutterb3q1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8qgOFt7qDQc644pMY1Wy-d87WmQc_sAE',
    appId: '1:748534742676:ios:6cbda1a40c9c117020fe81',
    messagingSenderId: '748534742676',
    projectId: 'flutter-project-61700',
    storageBucket: 'flutter-project-61700.firebasestorage.app',
    iosBundleId: 'com.example.flutterb3q1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmOgPeJNmQbDN1UC2kjIFw0H1wkVN_X0Y',
    appId: '1:748534742676:web:c5eb5f17f259454620fe81',
    messagingSenderId: '748534742676',
    projectId: 'flutter-project-61700',
    authDomain: 'flutter-project-61700.firebaseapp.com',
    storageBucket: 'flutter-project-61700.firebasestorage.app',
    measurementId: 'G-MTWPCRWDQG',
  );
}
